== 職務経歴書

=== 基本情報

[options="header"]
|===============================================================
| key | value

| name | すずき ただし
| Blog | http://tadashi.hatenablog.com/[聞こえないJavaエンジニアが適当に書き連ねていく]
| Twitter | https://twitter.com/tada_suzu[@tada_suzu]
| Qiita | https://qiita.com/deaf_tadashi[@deaf_tadashi]
|===============================================================

==== 留意事項
* 聴覚障害を持っているため、電話応対や多人数での会議は不得意です。会話時は、1対1、あるいは1対2などの少人数でのやり取りを望みます。
** 多人数での打ち合わせ時は、チャットなどの文字起こしがあると助かります。
* 聴覚障害に関する通院はありませんが、補聴器が破損した時に突然の半休を取る可能性があります。（数年に1度くらい、事前調整可能）

=== スキル

==== 言語
* プログラミング言語
** Java

2019年にJava11で新規開発を始めました。
Java8での業務経験なしで、Java7からJava11にステップアップしたのでラムダ式は不得意です。

** Kotlin
遊びで少々触ったことがある程度です。

** Scala
チュートリアルをちょっとやってみたレベルです。

** Web周り

スタイルシートやJavaScriptは必要に応じて調べながら簡単なものを書ける程度です。

** COBOL

5年ほど、開発に従事した経験がありますが、今はコードはうろ覚えで読めます。書くことはできません。

** shell

JOB起動用の簡単なshellスクリプトは書いた経験があります。

** AsciiDoc、Markdown

存在を知ってから、個人的な資料や打ち合わせ資料をAsciiDoc、あるいはMarkdownで書くようになりました。 +
設計書はまだどう書けばいいのか明確な答えが見えていないため、従来の書き方（Excelベース）で書き続けています。

** データベース

*** IBM DB2
*** Oracle 11g

いずれも、基本的なSQLは書けます。 +
データベースの構築は、マニュアルを読みながらであれば手を動かせる、程度です。 +
ER図を使った設計も行えます。

* 日本語

ネイティブ

* 英語

Google翻訳や辞書を片手に、プログラミング関連の内容はかろうじて読める程度です。

* 手話

簡単な日常会話なら出来ますが、お仕事の話になると手話表現がほぼわかりません。


==== フレームワーク
* Struts1.1
* Seasar2 + S2Dao

いずれも、フレームワークをベースに業務用のフレームワークを開発し、運用まで対応しています。

* Spring Boot 1系

2か月程、業務応援に行った先で使っていました。 +
業務応援はAPIの新規開発とテストを実施していたので、Springの機能は深く触っていません。

2018年度の新人研修用に、Struts1.1で作成された教材をSpring boot 1.5で書き直しました。

* Spring Boot 2.1.x

現在携わっている新規システムの開発で使用中です。
知識不足のため、毎日調べながら試行錯誤しています。

* JUnit
JUnit4.x系列は業務で少々用いましたが、業務全体に普及までは出来ませんでした。JUnitの便利さについての啓蒙が足りませんでした。
JUnit5.x系列は現在関わっている新規プロジェクトの簡単なプログラムテストで使っています。

=== その他

** 関わったJavaプロジェクトでは基盤部分の開発から担当していました。
** 開発ツールの選定や使い方の教育についても担当していました。
** プロジェクトではコードレビューをお願いされることが多い立場でした。
** パフォーマンスチューニング（SQL、Java）も必要に応じて対応していました。
*** SQLの書き方を改善、あるいはインデックスの付与を実施。
*** Javaロジックの見直し、必要に応じてリファクタリングを実施。


=== 強み

* プロジェクトの基盤部分をお願いされることが多い立場上、
フレームワークのコードやJavaのコアな部分を読むことも苦にしません。
* プロジェクトのサブリーダーという位置づけで要員教育を数年やってきた経験があります。


=== 弱み
* チームでのgitフローの経験がありません。
** subversionでの運用止まりです。
* 業務で新しいことをやる機会がないため、ちょっと触ったことがある程度の知識が多いです。

=== やったことはないが、興味があるもの
* クラウドで動くアプリケーション構築
* Dockerを使ったプロジェクト開発
** Dockerの自習は職場の端末でやったことがありますが、ネットワーク周りがうまくいかず、開発で使えるところまでいけていません。

== 登壇歴
* JJUG CCC 2016 fall
** JMH超入門 というテーマで20分お話しました。

* JJUC CCC 2019 Spring
** スキマ分野で生き残るための戦略 というテーマで20分お話ししました。

== 職務経歴

=== 2019年1月頃～現在
==== 業務内容
音楽会社の基幹システムの再構築プロジェクトにシステム基盤の開発及び、プログラマ支援という立場で関わっています。
画面やバッチ処理の基本設計には深く関わっていません。

現在のプロジェクトは経験が少ないメンバーが多いため、質問があったときは一緒に手を動かしながら原因を究明していくことが多いです。

==== 環境
* プログラミング言語
** Java11 + Spring Boot 2.1.x（Spring Boot 2.2へのバージョンアップは検討中）

* データベース
** IBM Db2

=== 2017年11月、12月
==== 業務内容
Spring Boot 1.4で新規開発を行っているプロジェクトの開発支援に行きました。 +
APIの新規開発とテストを担当していました。

==== 環境

* プログラミング言語
** Java8 + Spring Boot 1.4

* データベース
** PostgreSQL

=== 2014年1月～2019年1月頃まで
==== 業務内容
音楽会社の販売管理システムの再構築を経て、維持・ユーザー要望対応を担当していました。 +
前プロジェクトが中断する前から要件定義が始まっており、参画した時点では要件定義がほぼ完了していました。 +
システムの基盤、画面・バッチのプロトタイプ開発、技術調査を経て、今は基本設計、詳細設計、実装、テストとすべてを担当していました。

その他、音楽会社の社内システムの一部機能を別の社内システムに移植、Chrome対応などの細かい案件も担当しました。 +
細かい案件では私が実際に手を動かすことはほとんどなく、事前の調査及び修正方針決め、進捗管理を担当しました。

2016年後半からスポット的に、お客様の環境で動いていたシステムの改修を依頼されることがあります。 +
システムの作りについてはお客様もすべてを把握しているわけではないため、コードを読みながら修正箇所を確認して対応していました。

==== 環境

* サーバー
** Linux + Tomcat7
** Windows Server + Tomcat 8.5

* プログラミング言語
** Java7 + seasar2(をベースにしたフレームワーク)
** Java8 + Struts1(をベースにした他社開発のフレームワーク)

* データベース
** Oracle11g
** IBM Db2

=== 2013年9月 ～ 2013年12月
==== 業務内容
自社システムのリプレース対応（会社都合により中断）を担当しました。 +
前業務終了前から続いていたプロジェクトにプログラマとして参画しましたが、プロジェクトそのものが中断となりました。 +
プロジェクト内では、システム基盤として技術調査・プロトタイプの開発を行っていました。

==== 環境

* サーバー
** GlassFish

* プログラミング言語
** Java7 + オリジナルフレームワーク
*** オリジナルフレームワークは先人が開発したものをカスタマイズしようとしていた矢先にプロジェクトが中止。

* データベース
** PostgreSQL

=== 2002年4月 ～ 2013年9月
==== 業務内容
音楽関係の物流会社が運営している、物流パッケージシステムの開発、維持を行いました。

入社当初はIBM汎用機＋COBOLのシステムでしたが、2006年頃に画面をWeb化、2008年頃にホストをオープン系にリプレースしました。
両方のプロジェクトに主担当として関わっております。

画面のWeb化時はシステム基盤を担当するプログラマ、ホストのリプレース時は画面側の進捗管理を担当しつつ、技術調査・実装を担いました。
システムの総合テスト等も経験しております。

最後の1年間は客先に常駐し、開発担当チームのリーダーとしてチームを率いていました。

==== 環境

* サーバー

** IBM汎用機(2002年4月～2008年頃まで)
** Linux + Websphere(2008年頃～2013年)

* プログラミング言語
** COBOL
** Java1.6 + struts1.1

* データベース
** IBM DB2
